version: '3.8'

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:

services:
  to-do-application:
    container_name: to-do-application
    build: .
    ports:
      - "8082:8081"
    depends_on:
      - mysql-db
    networks:
      - todo-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Auto-create tables (Optional)
  
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
    ports:
      - "3307:3306"
    networks:
      - todo-network
    volumes:
      - mysql-data:/var/lib/mysql